mysite/urls.py
from django.contrib import admin
from django.urls import include, path

from nasrulhifz.views import SignUp
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('nasrulhifz/', include('nasrulhifz.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', SignUp.as_view(), name='signup'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

nasrulhifz/urls.py
from django.urls import path

from . import views
from django.contrib.auth.decorators import login_required
from rest_framework.authtoken.views import obtain_auth_token
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings

app_name = 'nasrulhifz'

urlpatterns = [
    # Web app related URI
    path('', login_required(views.IndexView.as_view()), name='index'),
    path('<int:surah_number>/ayats/', login_required(views.AyatListView.as_view()), name="ayatlist"),
    path('enter/', views.enter, name='enter'),
    path('revise/', views.revise, name='revise'),
    path('<int:surah_number>/ayats/<int:ayat_number>/', views.detail, name="detail"),

    # API related uri
    path('api/', views.HifzList.as_view()),
    path('api/delete/<int:surah_number>/<int:ayat_number>/', views.HifzDeleteSingle.as_view()),
    path('api/delete/', views.HifzDeleteMultiple.as_view()),
    path('api/quranmeta/list/', views.QuranMetaList.as_view()),
    path('api/quranmeta/<int:surah_number>/<int:ayat_number>/', views.QuranMetaDetail.as_view()),
    path('api/surahmeta/<int:surah_number>/', views.SurahMetaDetail.as_view()),
    # path('api/revise/', views.ReviseList.as_view()),
    path('api/revise/', views.ReviseCustomView.as_view()),
    path('api/revise_no_user/', views.ReviseNoUser.as_view(), name='revise_no_user'),


    # Authentication for API
    path('api-token-auth/', views.ObtainAuthToken.as_view()),
    path('api-auth/', include('rest_framework.urls')),
    path('api/register/', views.CreateUserView.as_view()),

    # password reset api
    # path('api/password_reset/', include('django_rest_passwordreset.urls'), name='password_reset'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.DATA_URL, document_root=settings.DATA_ROOT)

nasrulhifz/forms.py
from django import forms
from django.forms import formset_factory

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core import validators

class CustomUserCreationForm(UserCreationForm):
    # username = forms.CharField(max_length=30)
    email = forms.EmailField(max_length=200)

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2', )

    def __init__(self , *args, **kwargs):
        super(UserCreationForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control form-control-lg m-4 custom-size'
            # if visible.field == self.fields['username']:
            #     visible.field.widget.attrs['placeholder'] = 'Username'

            if visible.field == self.fields['email']:
                visible.field.widget.attrs['placeholder'] = 'Email'

            if visible.field == self.fields['password1']:
                visible.field.widget.attrs['placeholder'] = 'Enter Password'

            if visible.field == self.fields['password2']:
                visible.field.widget.attrs['placeholder'] = 'Reenter Password'
    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.username = user.email
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


# unused
class ReviseForm(forms.Form):
    unit_number = forms.IntegerField(min_value=1, max_value=30, widget=forms.NumberInput(
        attrs={
            'type': 'number',
            'class': 'mb-4 form-control custom-size',
            'id': 'unit-number',
            'name': 'unit-number',
            'placeholder': 'Juz Number',
            'aria-describedby': 'UnitNumberWarning'
        }

        ))



class HifzForm(forms.Form) :
    surah_number = forms.IntegerField(min_value=1, max_value=114, widget=forms.NumberInput(attrs={
            'class': 'form-control form-control-lg',
            'placeholder': 'Surah Number',
            'name': 'surah_number',
            'id': 'surah-number-form'
        }))
    ayat_number = forms.IntegerField(min_value=1, max_value=288, widget=forms.NumberInput(attrs={
            'class': 'form-control form-control-lg surah-param-inputs',
            'placeholder': 'Ayat Number',
            'name': 'ayat_number',
            'id': 'ayat-number-input',
        }), required=False)

    min_range = forms.IntegerField(min_value=1, max_value=288, widget=forms.NumberInput(attrs={
            'class': 'form-control form-control-lg surah-param-inputs',
            'placeholder': 'Lower Bound',
            'name': 'lower_bound',
            'id': 'min-limit-input',
        }), required=False)

    max_range = forms.IntegerField(min_value=1, max_value=288, widget=forms.NumberInput(attrs={
            'class': 'form-control form-control-lg surah-param-inputs',
            'placeholder': 'Upper Bound',
            'name': 'upper_bound',
            'id': 'max-limit-input',
        }), required=False)


class WordIndexForm(forms.Form):
    index = forms.IntegerField(
        label='Word Index',
        widget=forms.NumberInput(attrs={
            'class': 'form-control',
            'placeholder': 'Word Index',
            'aria-label': 'Word Index',
            'aria-describedby': 'basic-addon2',
            'name': 'index',

            }),
        min_value=1,

        )

WordIndexFormSet = formset_factory(WordIndexForm, extra=1)

nasrulhifz/views.py
from django.http import HttpResponseRedirect, Http404, JsonResponse, HttpResponseNotFound, HttpResponse
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy

from django.contrib import messages


from .models import Hifz, QuranMeta, WordIndex, SurahMeta
from .serializers import *
from .forms import HifzForm
from numpy import take

from django.contrib.auth.decorators import login_required
from django.views.generic.edit import FormView

import random
from datetime import date

from .forms import CustomUserCreationForm, ReviseForm

from rest_framework import generics, status, mixins, parsers, permissions, renderers
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.exceptions import NotFound
from rest_framework.authtoken.models import Token

from os.path import join

import sqlite3



from .permissions import IsOwner
from django.contrib.auth.models import User


class CreateUserView(generics.CreateAPIView):
    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        try:
            serializer.is_valid(raise_exception=True)
            self.perform_create(serializer)
        except Exception as E:
            print(E)
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
        headers = self.get_success_headers(serializer.data)
        return Response(serializer.data, status=status.HTTP_201_CREATED, headers=headers)

    model = User
    permission_classes = [
        permissions.AllowAny # Or anon users can't register
    ]
    serializer_class = UserSerializer

class SignUp(generic.CreateView):
    # form_class = UserCreationForm
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'



    def form_valid(self, form):
        messages.success(self.request, "You are registered! Please enter your login details to continue.",extra_tags='alert alert-success custom-size')
        return super().form_valid(form)


class IndexView(generic.ListView):
    template_name = 'nasrulhifz/index.html'
    context_object_name = 'latest_quran_data'

    login_url = '/login/'
    redirect_field_name = 'redirect_to'

    def get_queryset(self):
        hifz_list = Hifz.objects.filter(hafiz=self.request.user).order_by('surah_number').values(
            'surah_number').distinct()
        if len(hifz_list) == 0:
            return None

        surah_meta_list = []
        for hifz in hifz_list:
            surah_meta_list.append(getSurahString(hifz.get('surah_number')))

        data = zip(hifz_list, surah_meta_list)
        # print(hifz_list)
        return data


class AyatListView(generic.ListView):
    template_name = 'nasrulhifz/ayatlist.html'
    context_object_name = 'ayat_list_for_surah'

    def get_queryset(self): 
        # hifz = get_object_or_404(Hifz, pk=self.kwargs['pk'])
        # return Hifz.objects.filter(surah_number=hifz.surah_number)
        hifz_list = Hifz.objects.filter(hafiz=self.request.user, surah_number=self.kwargs['surah_number'])
        for hifz in hifz_list:
            hifz.last_refreshed_period_string = hifz.get_last_refreshed_timelength()
            hifz.days_since_last_refreshed = hifz.get_number_of_days_since_refreshed()
            hifz.average_difficulty = "{0:.2f}".format(hifz.get_hifz_average_difficulty())

        return hifz_list

    def post(self, request, *args, **kwargs):
        surah_number = request.POST.get('surah_number')[0]
        ayat_number_list = request.POST.getlist('ayat_number')

        if surah_number:
            surah_number = int(surah_number)
            ayat_number_list = [int(n) for n in ayat_number_list]
            for ayat_number in ayat_number_list:
                h = Hifz.objects.filter(hafiz=request.user, surah_number=surah_number, ayat_number=ayat_number)
                h = h[0]
                h.last_refreshed = date.today()
                h.save()

            hifz_list = Hifz.objects.filter(hafiz=request.user, surah_number=surah_number)

            for hifz in hifz_list:
                hifz.last_refreshed_period_string = hifz.get_last_refreshed_timelength()
                hifz.days_since_last_refreshed = hifz.get_number_of_days_since_refreshed()
                hifz.average_difficulty = "{0:.2f}".format(hifz.get_hifz_average_difficulty())

            return render(request, 'nasrulhifz/ayatlist.html', {self.context_object_name: hifz_list})
        else:
            return Http404()

# API for creating, updating, saving new hifzs
class HifzList(mixins.ListModelMixin, mixins.CreateModelMixin, mixins.UpdateModelMixin, mixins.DestroyModelMixin, generics.GenericAPIView):
    serializer_class = HifzSerializer
    permission_classes = (IsOwner,)

    def get_queryset(self):
        surah_number = self.request.query_params.get('surah_number', None)
        juz_number = self.request.query_params.get('juz_number', None)
        ayat_number = self.request.query_params.get('ayat_number', None)
        if surah_number is not None and ayat_number is not None:
            return Hifz.objects.filter(hafiz=self.request.user, surah_number=surah_number, ayat_number=ayat_number)
        if surah_number is not None:
            return Hifz.objects.filter(hafiz=self.request.user, surah_number=surah_number)
        if juz_number is not None:
            return Hifz.objects.filter(hafiz=self.request.user, juz_number=juz_number)

        return Hifz.objects.filter(hafiz=self.request.user)


    def get(self, request, *args, **kwargs):
        return self.list(self, request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = parsers.JSONParser().parse(request)
        if isinstance(data, list):
            serializer = self.get_serializer(data=data, many=True)
        else:
            serializer = self.get_serializer(data=data)
        if serializer.is_valid():
            serializer.save(hafiz=request.user)
            return JsonResponse(serializer.data, safe=False, status=201)
        else:
            return JsonResponse(serializer.errors, safe=False, status=400)

    def patch(self, request, *args, **kwargs):
        data = parsers.JSONParser().parse(request)
        if isinstance(data, list):
            objs = Hifz.objects.filter(hafiz=self.request.user)
            for d in data:
                d['hafiz'] = {'username': self.request.user.username}
            serializer = self.get_serializer(instance=objs, data=data, many=True, partial=True)
        else:
            try:
                obj = Hifz.objects.get(hafiz=self.request.user,
                                       surah_number=data.get('surah_number'),
                                       ayat_number=data.get('ayat_number'))
                serializer = self.get_serializer(instance=obj, data=data)
            except:
                raise NotFound('Hifz to be updated does not exist.')
        if serializer.is_valid():
            serializer.save()
            return JsonResponse(serializer.data, safe=False, status=201)
        else:
            return JsonResponse(serializer.errors, safe=False, status=400)
    


class HifzDeleteMultiple(generics.GenericAPIView, mixins.DestroyModelMixin):
    serializer_class = HifzSerializer
    permission_classes = (IsOwner,)

    def patch(self, request, *args, **kwargs):
        data = parsers.JSONParser().parse(request)
        for d in data:
            if d.get('surah_number') == None or d.get('ayat_number') == None:
                return HttpResponseBadRequest("Either ayat number or surah number is missing in body.")
            try:
                hobj = Hifz.objects.get(hafiz=self.request.user, surah_number=d['surah_number'], ayat_number=d['ayat_number'])
                hobj.delete()
            except:
                raise NotFound('Hifz for deletion does not exist.')
        
        return HttpResponse("Deletion successfull.")





class HifzDeleteSingle(generics.DestroyAPIView):
    serializer_class =  HifzSerializer
    model = Hifz
    permission_classes = (IsOwner,)


    def get_object(self):
        surah_number = self.kwargs.get('surah_number')
        ayat_number = self.kwargs.get('ayat_number')
        try:
            return Hifz.objects.get(hafiz=self.request.user,
                                surah_number=surah_number,
                                ayat_number=ayat_number)
        except:
            raise NotFound('Hifz for deletion does not exist.')
    
    def destroy(self, request, *args, **kwargs):
        instance = self.get_object()
        surah_number = instance.surah_number
        ayat_number = instance.ayat_number
        self.perform_destroy(instance)
        return HttpResponse('Deletion surah number: {}  ayat: {} succeeded'.format(surah_number, ayat_number))



class QuranMetaList(generics.ListAPIView):
    serializer_class = QuranMetaSerializer
    queryset = QuranMeta.objects.all()
    def get_queryset(self):
        queryset = QuranMeta.objects.all()
        surah_number = self.request.query_params.get('surah_number', None)
        juz_number = self.request.query_params.get('juz_number', None)
        if surah_number is not None:
            queryset = queryset.filter(surah_number=surah_number)
            return queryset
        elif juz_number is not None:
            queryset = queryset.filter(juz_number=juz_number)
            return queryset
        else:
            return None


class QuranMetaDetail(generics.RetrieveAPIView):
    serializer_class = QuranMetaSerializer
    model = QuranMeta

    def get_object(self):
        # this how we fetch the parameter from the url format, specified in url.py
        surah_number = self.kwargs.get('surah_number')
        ayat_number = self.kwargs.get('ayat_number')

        return QuranMeta.objects.get(surah_number=surah_number, ayat_number=ayat_number)

nasrulhifz/templates/nasrulhifz/ayatdisplay.html
{% load ayat_extras%}


<div class="text-center">
    <button type="button" class="btn btn-light"><h2 class="uthm2">{{ surah_name }}</h2></button>

</div>

<br>
    
    <canvas id="myCanvas" ></canvas>

<script>
    img = new Image()

    img.src = "{{ image_url }}"

   wordShown = false
    $("#show-ayat-button").click(function(){
        var c = document.getElementById("myCanvas");
        var ctx = c.getContext("2d");
        ctx.clearRect(0, 0, c.width, c.height)
        c.width = img.naturalWidth
        c.height = img.naturalHeight
        ctx.drawImage(img ,0,0)

        if(wordShown){
            scale = 1260 / img.width
            {% for data  in gcoords %}
                ctx.moveTo({{ data.0 }} / scale, {{ data.2 }} / scale)    
                ctx.lineTo({{ data.1 }} / scale, {{ data.2 }} / scale)
                ctx.lineTo({{ data.1 }} / scale, {{ data.3 }} / scale)
                ctx.lineTo({{ data.0 }} / scale, {{ data.3 }} / scale)
                ctx.lineTo({{ data.0 }} / scale, {{ data.2 }} / scale)    
                ctx.stroke()
            {% endfor %}
            wordShown = false
        } else {
            wordShown = true
        }
    })
    
    img.onload = function(){
        var c = document.getElementById("myCanvas");
        c.width = img.naturalWidth
        c.height = img.naturalHeight
        var ctx = c.getContext("2d");
        ctx.drawImage(img ,0,0)
        scale = 1260 / img.width
        {% for data  in gcoords %}
            ctx.moveTo({{ data.0 }} / scale, {{ data.2 }} / scale)    
            ctx.lineTo({{ data.1 }} / scale, {{ data.2 }} / scale)
            ctx.lineTo({{ data.1 }} / scale, {{ data.3 }} / scale)
            ctx.lineTo({{ data.0 }} / scale, {{ data.3 }} / scale)
            ctx.lineTo({{ data.0 }} / scale, {{ data.2 }} / scale)    
            ctx.stroke()
        {% endfor %}
    }

</script>

nasrulhifz/templates/nasrulhifz/ayatlist.html
{% extends "base_authenticated.html" %}


{% block content %}
    <div class="mb-4 text-align:left">
     <button class="btn btn-dark" onclick="GoBackWithRefresh();return false;">Back</button>
  </div>


    <input class="form-control my-4 " type="text" id="filter-input" onkeyup="filterTable()" placeholder="Search..">



{% if ayat_list_for_surah %}
	
    <form method="POST" action="{% url 'nasrulhifz:ayatlist' ayat_list_for_surah.0.surah_number %}">
        <input type="hidden" name="surah_number" value="{{ ayat_list_for_surah.0.surah_number }}">
        {% csrf_token %}

        <div class="text-center sticky-top"><button type="submit" class="btn btn-success">Update Refreshed Status</button></div>
    <table id="ayat-list-table"  class="my-4 table table-bordered table-hover table-style">
        <thead>

            <tr>
                <th style="text-align:center">Ayat Number</th>
                <th style="text-align:center">Average Difficulty</th>
                <th style="text-align:center">Last Time Refreshed</th>
                <th style="text-align:center">Refreshed ?</th>
            </tr>
        </thead>
        <tbody data-link="row" class="rowlink">
            {% for hifz in ayat_list_for_surah %}
            <tr>
                    <td align="center" class='clickable-row' data-href="{% url 'nasrulhifz:detail' hifz.surah_number hifz.ayat_number %}">{{ hifz.ayat_number }}</td>
                    <td align="center" class='clickable-row' data-href="{% url 'nasrulhifz:detail' hifz.surah_number hifz.ayat_number %}">{{ hifz.average_difficulty }}</td>
                    <td align="center" class='clickable-row' data-href="{% url 'nasrulhifz:detail' hifz.surah_number hifz.ayat_number %}">{{ hifz.days_since_last_refreshed }} days</td>
                    <td align="center">
                            <input type="checkbox" name="ayat_number" value="{{ hifz.ayat_number }}">
                            
                        </td>
            </tr>
            {% endfor %}
        </tbody>


    </table>
</form>

   



{%  else %}
	<p>No ayats are available.</p>
{% endif %}
{% endblock %}

nasrulhifz/templates/nasrulhifz/detail.html
{% extends "base_authenticated.html" %}
{% load ayat_extras%}



{% block content %}

<div class="mb-4 text-align:left">
     <button class="btn btn-dark" onclick="history.back(-1)">Back</button>
  </div>


    {% include "nasrulhifz/ayatdisplay.html" %}


<br>
    {% if messages %}
    {% for message in messages %}

    <div class="alert alert-success">
        {{message}}
    </div>

    {% endfor %}
    {% endif %}


{% endblock %}

nasrulhifz/templates/nasrulhifz/enter.html
{% extends "base_authenticated.html" %}

{% block content %}
 

<form method="GET" action="{% url 'nasrulhifz:enter' %}" >
	{% csrf_token %}
	<div class="d-flex justify-content-center row align-self-center">
		<div class="m-2 col-md-3 align-self-center">
			{{  hifzform.surah_number }}
		</div>
		<div class="m-2 col-md-3 align-self-center">
			{{  hifzform.ayat_number }}
		<div id="limit-forms" style="display: none;">
				{{  hifzform.min_range }}
			<br>
				{{  hifzform.max_range }}
			</div>
		</div>

		<div class="m-2 col-md-2 text-center align-self-center">
			<input id="ayat-mode-input" type="hidden" name="ayat-mode" value="ayat_number">
			<button id="limit-button" class="btn btn-outline-secondary" type="button">Enter Limits</button>


		</div>

		<div class="m-2 col-md-2 text-center align-self-center">
			<div class="form-group">
					<label for="diff">Set default difficulty for words:</label>
					<select class="form-control" id="diff" name="default_difficulty">
						<option>3</option>
						<option>2</option>
						<option>1</option>
					</select>
				</div>
		</div>


	</div>



	<br>

	<div class="d-flex justify-content-center">
	<button id="display-button" class="btn-primary btn" type="submit">
		Display Ayat
	</button>
	</div>

	<br>



	{% if display_with_meta %}

		<div class='mydiv'>
		<button id="close-display" type="button" class="close topleft" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
		{% include "nasrulhifz/ayatdisplay.html" %}
		</div>
		
	{% endif %}

  <div class="d-flex justify-content-center">
  		<button id="submit-button" class="btn-success custom-submit btn" type="submit" formmethod="post">
			{% if not hifz_exists %}
				Submit
			{% else %}
				Update
			{% endif %}
  		</button>
  </div>

  <br>



</form>



{% if messages %}
    {% for message in messages %}

    <div class="{{message.tags}}">
	  {{message}}
	</div>

    {% endfor %}
{% endif %}


{% endblock %}

nasrulhifz/templates/nasrulhifz/index.html
{% extends "base_authenticated.html" %}

{% block content %}
{% if latest_quran_data %}
	<div class="list-group">
		<a class="list-group-item list-group-item-primary text-center"><h2>Surah List</h2></a>
    {% for hifz, surah_name in latest_quran_data %}
        <a class="list-group-item list-group-item-action " href="{% url 'nasrulhifz:ayatlist' surah_number=hifz.surah_number %}"><p class="text-right uthm2"><b>{{ surah_name }}</b></p></a>
    {% endfor %}
    </div>
{% else %}
    <p>No hifz are available.</p>
{% endif %}

	
{% if message %}
<h2>{{ message }}</h2>
{% endif %}

{% endblock %}

nasrulhifz/templates/nasrulhifz/revise.html
{% extends "base_authenticated.html" %}

{% block content %}

{% if mode_select %}
<div class="row justify-content-center">
    <div class="col-md-12 align-self-center">
        Please select your mode of revision.
    </div>
</div>

<form id="reviseParameters" action="{% url 'nasrulhifz:revise' %}" method="POST">
    {% csrf_token %}
    <div class="my-4 row justify-content-center">
        <div class="btn-group btn-group-toggle" data-toggle="buttons">
            <!-- TODO: fix juz mode for revise page -->
<!--            <label class="btn btn-primary active">-->
<!--                <input type="radio" name="mode-select" id="juz_mode" value="juz_mode" autocomplete="off" checked> Juz Mode-->
<!--            </label>-->
            <label class="btn btn-primary">
                <input type="radio" name="mode-select" id="surah_mode" value="surah_mode" autocomplete="off" checked> Surah Mode
            </label>
            <label class="btn btn-primary">
                <input type="radio" name="mode-select" id="free_mode" value="free_mode" autocomplete="off"> Free Mode
            </label>
        </div>

    </div>


    <div class="row justify-content-center">
        <div class="mb-4 col-md-12 align-self-center">
            Please enter the streak length. (This is the number of test you will be given for your selected mode)
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-md-12 align-self-center">
            <input type="number" class="mb-4 form-control" id="streak-length" name="streak-length" placeholder="Streak Length" required="true">
            <input type="number" class="mb-4 form-control" id="unit-number" name="unit-number" placeholder="Surah Number" min="1" max="114" aria-describedby="UnitNumberWarning">


        </div>
    </div>

    <div class="row justify-content-center">
        <div class="mb-4 col-md-12 align-self-center">
            Please enter the number of ayats to be blinded around the tested ayat. (Example: if you want 1 ayat before and after the ayat tested to be blinded as well, enter 1 in this box.)
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-md-12 align-self-center">
            <input type="number" class="mb-4 form-control" id="blind-count" name="blind-count" value="1" max="4" min="1" required="true">
            <button  class="btn btn-outline-primary" type="submit">Start</button>
        </div>
    </div>



</form>

{% endif %}


{% if meta and meta|length > 0 %}

    <!-- The slideshow -->

    <div id="image-slider" class="splide">
        <div class="splide__track">
            <div class="splide__list">
                {% for url, boundary_list, surah_name, surah_number, ayat_number in meta %}
                    <div class="splide__slide">
                        {% include "nasrulhifz/revisiondisplay.html" %}
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>












{% endif %}

{% if not meta and not mode_select %}

<h1>No hifz matches those criteria.</h1>

{% endif %}


{% endblock %}

nasrulhifz/templates/nasrulhifz/revisiondisplay.html
<div>


<div class="text-center my-4">
    <button type="button" class="label-button btn btn-light"><p class="uthm2">{{ surah_name }}</p></button>
    {% comment %} <p id="surah-number" hidden >{{ hifzinfo.surah_number }}</p> {% endcomment %}
    <button id="ayat-number" type="button" class="label-button btn btn-light">{{ ayat_number }}</button>
</div>

    <div>
        <img   class="page" src="{{ url }}" usemap="#pageblocks{{forloop.counter}}"  id="testImage{{forloop.counter}}"  style="width:100%; height:auto" >
    </div>

<map name="pageblocks{{forloop.counter}}">
        {% for data in boundary_list %}
            <area shape="rect" color="black" part="{{surah_number}}_{{ayat_number}}_{{forloop.counter}}" href="#" coords="{{ data.0 }}, {{ data.2 }}, {{ data.1 }} - {{ data.0 }}, {{ data.3 }} - {{ data.2 }} ">
        {% endfor %}
</map>

</div>